### ISSUE TITLE
zlibrary的两个线路都无法打开了，请老师看一下。

### ISSUE THREAD

**Issue by codyyuan413** [monthlyliaoyuan/Unofficial_Z_Access#15]
![3333](https://github.com/user-attachments/assets/411f1c52-220a-4bcd-9acb-8e4a97d7d54f)
![22222](https://github.com/user-attachments/assets/6d36ce8f-ee0d-4ed8-af41-c1a1c39a479b)

**Comment by louiesun** [comment]
问题找到了：zlibrary换域名了，别急，很快解决。跟gfw没关系（可能和美国的有关系）。

**Comment by codyyuan413** [comment]
好的 多谢大佬，我以为这个方式被gfw破解了呢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月22日(周二) 晚上8:17
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [monthlyliaoyuan/Unofficial_Z_Access] zlibrary的两个线路都无法打开了，请老师看一下。 (Issue #15)




 
问题找到了：zlibrary换域名了，别急，很快解决。跟gfw没关系（可能和美国的有关系）。

**Comment by codyyuan413** [comment]
没问题的，大佬。多谢。坐标：山东



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月22日(周二) 晚上8:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [monthlyliaoyuan/Unofficial_Z_Access] zlibrary的两个线路都无法打开了，请老师看一下。 (Issue #15)




  
好的 多谢大佬，我以为这个方式被gfw破解了呢
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年10月22日(周二) 晚上8:17 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [monthlyliaoyuan/Unofficial_Z_Access] zlibrary的两个线路都无法打开了，请老师看一下。 (Issue #15) 问题找到了：zlibrary换域名了，别急，很快解决。跟gfw没关系（可能和美国的有关系）。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
V10.0.1好了，你看看行不行。上海教育网可以。

**Comment by louiesun** [comment]
https://github.com/monthlyliaoyuan/Unofficial_Z_Access/blob/master/DOMAINconfig.txt

我不知道你怎么改失败的
